
# Detect build architecture
BUILDARCH ?= $(shell uname -m)
ifeq ($(BUILDARCH),aarch64)
    BUILDARCH=arm64
endif
ifeq ($(BUILDARCH),x86_64)
    BUILDARCH=amd64
endif

ifneq ($(wildcard user.env),)
include user.env
endif

# Use containerized environment
CONTAINER?=0
CONTAINER_ENGINE ?= docker

CONTAINER_IMAGE_NAME ?= calaos_builder_image
CONTAINER_TAG ?= latest
CONTAINER_COMMAND := ${CONTAINER_ENGINE} run -it --rm \
		--volume="$(CURDIR):$(CURDIR)" \
		-v calaos-builder-build:$(CURDIR)/build \
		--workdir="$(CURDIR)" \
		$(if $(CALAOS_SRC_PATH),--volume="$(CALAOS_SRC_PATH):$(CALAOS_SRC_PATH)",) \
		$(CONTAINER_IMAGE_NAME):$(CONTAINER_TAG)

BUILDROOT_VERSION ?= 2025.02.x

#MACHINE ?= network_player_v2
#MACHINE ?= raspberrypi_zero2w
MACHINE ?= luckfox_pico_86panel_w

CONFIG_NAME=${MACHINE}_defconfig
CONFIG_FILE?=buildroot-external/configs/${CONFIG_NAME}
OUTPUT_DIR?=../output/${MACHINE}
OUTPUT_ABS_DIR=$(CURDIR)/build/output/$(MACHINE)
EXTERNAL_REPOSITORIES?=../../buildroot-external
BUILD_VERSION ?=  $(shell git describe --tags --dirty --always 2>/dev/null || echo "unknown")

# Optional: override calaos-remote-ui source with a local path
CALAOS_SRC_PATH ?=
BR2_OVERRIDE_FILE ?=
ifneq ($(CALAOS_SRC_PATH),)
    BR2_OVERRIDE_FILE = $(CURDIR)/build/local.mk
endif

ifeq ($(CONTAINER), 1)
	DEPS = container-image
	PREFIX = $(CONTAINER_COMMAND)
else
	DEPS =
	PREFIX =
endif

### DEFAULT TARGET ###

# Generate local.mk with source override when CALAOS_SRC_PATH is set
build/local.mk:
ifneq ($(CALAOS_SRC_PATH),)
	mkdir -p build
	echo "CALAOS_REMOTE_UI_OVERRIDE_SRCDIR = $(CALAOS_SRC_PATH)" > build/local.mk
endif
.PHONY: build/local.mk

BR2_EXTRA_OPTS = $(if $(BR2_OVERRIDE_FILE),BR2_PACKAGE_OVERRIDE_FILE=$(BR2_OVERRIDE_FILE),)

build: $(DEPS) br-downloads $(if $(CALAOS_SRC_PATH),build/local.mk,) config ## Build target.
	@echo ">>> Build target [${MACHINE}]"
	$(PREFIX) make -C build/buildroot-${BUILDROOT_VERSION} BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) O=$(OUTPUT_DIR) $(BR2_EXTRA_OPTS)
.PHONY: build

sdk: build ## Build target.
	@echo ">>> Build SDK [${MACHINE}]"
	$(PREFIX) make -C build/buildroot-${BUILDROOT_VERSION} BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) O=$(OUTPUT_DIR) BR2_SDK_PREFIX=sdk-${MACHINE}-${BUILD_VERSION} sdk $(BR2_EXTRA_OPTS)
.PHONY: build

build-%: $(DEPS) br-downloads $(if $(CALAOS_SRC_PATH),build/local.mk,) ## Build specific package
	@echo ">>> Build package [$*] for target [${MACHINE}]"
	$(PREFIX) make -C build/buildroot-${BUILDROOT_VERSION} BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) O=$(OUTPUT_DIR) $* $(BR2_EXTRA_OPTS)
.PHONY: build-%

config: $(DEPS) $(if $(CALAOS_SRC_PATH),build/local.mk,)
	$(PREFIX) make -C build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) $(CONFIG_NAME) $(BR2_EXTRA_OPTS)
.PHONY: config

menuconfig: $(DEPS)
	$(PREFIX) make -C build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) $(CONFIG_NAME) $(BR2_EXTRA_OPTS)
	$(PREFIX) make -C build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) menuconfig $(BR2_EXTRA_OPTS)
	$(PREFIX) make -C build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) savedefconfig DEFCONFIG=$(abspath $(CONFIG_FILE))
.PHONY: menuconfig

clean: ## Clean output repository. It will wipe out all the intermediary files generated by buildroot
	rm -rf "$(CURDIR)/build/output"
.PHONY: clean

###Distribution rules ###
DESTDIR?=./build/distribution/${MACHINE}

${DESTDIR}:
	mkdir -p ${DESTDIR}

.PHONY: distrib

distrib-clean: ## Remove the distribution directory
	rm -rf ${DESTDIR}

### DOWNLOAD Buildroot ###
build/.stamp-br-downloads:
	@echo ">>> Download buildroot source code"
	$(PREFIX) mkdir -p build
	git clone https://gitlab.com/buildroot.org/buildroot.git build/buildroot-${BUILDROOT_VERSION}
	git -C build/buildroot-${BUILDROOT_VERSION} checkout ${BUILDROOT_VERSION}
	### $(PREFIX) curl -s https://buildroot.org/downloads/buildroot-${BUILDROOT_VERSION}.tar.gz | tar xz -C build/
	touch build/.stamp-br-downloads

br-downloads: build/.stamp-br-downloads ## Download buildroot source code
.PHONY: br-downloads

### bootstrap ###
bootstrap:
	sh ./bootstrap.sh

### CONTAINER RULES ###

container-image: Dockerfile ## Build Docker image
	@${CONTAINER_ENGINE} build \
		--ssh=default \
		--build-arg="USER_UID=$(shell id -u)" \
		--build-arg="USER_GID=$(shell id -g)" \
		--build-arg="PROJECT_PATH=$(CURDIR)" \
		--tag=$(CONTAINER_IMAGE_NAME):$(CONTAINER_TAG) \
		.
.PHONY: container-image

containter-shell: container-image ## Run shell in container
	@$(CONTAINER_COMMAND) /bin/bash
.PHONY: container-shell

container-rm: ## Remove Docker image
	@${CONTAINER_ENGINE} image rm $(CONTAINER_IMAGE_NAME):$(CONTAINER_TAG)
.PHONY: container-rm

### SUPPORT RULES ###
help:           ## Show this help.
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "\033[36m%-30s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
.PHONY: help


.DEFAULT_GOAL := help
